// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package handler_test is a generated GoMock package.
package handler_test

import (
	reflect "reflect"

	processor "github.com/floriantoufet/overlap/internal/processor"
	gomock "github.com/golang/mock/gomock"
)

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// PrintOverlapRelation mocks base method.
func (m *MockProcessor) GetOverlapRelation(cidrA, cidrB string) (processor.NetworkRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrintOverlapRelation", cidrA, cidrB)
	ret0, _ := ret[0].(processor.NetworkRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrintOverlapRelation indicates an expected call of PrintOverlapRelation.
func (mr *MockProcessorMockRecorder) GetOverlapRelation(cidrA, cidrB interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintOverlapRelation", reflect.TypeOf((*MockProcessor)(nil).GetOverlapRelation), cidrA, cidrB)
}
