name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
      - name: Test unit
        run: go test -v ./...
      - name: Integration test
        run: go install github.com/cucumber/godog/cmd/godog@v0.12.5 && go mod download && go build -o test/godog/overlap main.go && cd test/godog && go mod download && godog run
